version: '3.8'
services:

  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - storytranslatorreactdotnet

  db:
    image: postgres:16-bullseye
    restart: always
    environment:
      - POSTGRES_DB=storytranslatorreactdotnet
      - POSTGRES_USER=storytranslatorreactdotnet
      - POSTGRES_PASSWORD=storytranslatorreactdotnet
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - storytranslatorreactdotnet

volumes:
  db:
    driver: local

networks:
  storytranslatorreactdotnet:
    driver: bridge
